version: "3.4"

services:
  ip2country:
    image: "nexus-ng.themarker.com/ip2country:${version:-latest}"
    hostname: ip2counrty
    networks:
      - production
    ports:
      - "4005:8080"
networks:
  production:
    external: true
